version: '3.7'

services:
  bridge-back:
    container_name: bridge-back
    build: .
    ports:
      - 3001:3001
      - 9229:9229
    env_file:
      - .env
    depends_on:
      - bridge-postgres

  bridge-postgres:
    container_name: bridge-postgres
    image: postgres:11
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432

networks:
  default:
    external:
      name: bridge-net
